name: build

on:
  pull_request:
    paths-ignore:
      - ".github"
  push:
    branches:
      - main
    paths-ignore:
      - ".github"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true # tmp

      - name: fmt
        run: make fmt

      - name: Build
        run: make build
