name: "[all] lint"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install commitlint
        run: |
          pnpm install

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        env:
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          COMMITS: ${{ github.event.pull_request.commits }}
        run: |
          npx commitlint \
            --from "${HEAD_SHA}"~"${COMMITS}" \
            --to "${HEAD_SHA}" \
            --verbose

      - name: Validate PR name with commitlint
        if: github.event_name == 'pull_request'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "${PR_TITLE}" | npx commitlint
