name: OSV Scanner

on:
  schedule:
    - cron: "17 22 * * 6"

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  scan-scheduled:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@19ec1116569a47416e11a45848722b1af31a857b" # v1.9.0
    with:
      scan-args: |-
        -r
        --skip-git
        ./
