name: OSV Scanner

on:
  push:
    branches: ["main"]

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  scan-scheduled:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@3c399db9dd6dd8106a27d280d53c55077d3f7cea" # v1.8.1
    with:
      scan-args: |-
        -r
        --skip-git
        ./
