name: OSV Scanner

on:
  schedule:
    - cron: "17 22 * * 6"

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  scan-scheduled:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@678a866dcba398c8ed0124a09928d250f187b52a" # v1.8.4
    with:
      scan-args: |-
        -r
        --skip-git
        ./
