name: OSV Scanner

on:
  schedule:
    - cron: "17 22 * * 6"

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  scan-scheduled:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@f0e6719deb666cd19a0b56bc56d01161bd848b4f" # v1.8.5
    with:
      scan-args: |-
        -r
        --skip-git
        ./
