name: Release

on:
  pull_request:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: linux-amd64
            goos: linux
            goarch: amd64
            os: ubuntu-latest
          - target: apple-darwnin-silicone
            goos: darwin
            goarch: arm64
            os: macos-latest
          - target: apple-darwnin-intel
            goos: darwin
            goarch: amd64
            os: macos-latest
    env:
      ARTIFACT_NAME: clickup-tui-${{ matrix.target }}-${{ github.event.release.tag_name }}.tar.gz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true # tmp

      - name: Build the binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: CGO_ENABLED=1 go build -o bin/clickup-tui

      - name: "Tar files"
        working-directory: bin
        run: tar -czvf "${ARTIFACT_NAME}" clickup-tui

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} bin/"${ARTIFACT_NAME}"

  homebrew:
    needs: release
    name: Bump Homebrew formula
    # Skip this job in case of git pushes to prerelease tags
    if: ${{ github.event_name != 'push' || !contains(github.ref, '-') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: clickup-tui
          formula-path: Formula/clickup-tui.rb
          homebrew-tap: prgres/homebrew-formulae
          base-branch: main
          tag-name: ${{ env.VERSION }}
          download-url: https://github.com/prgres/clickup-tui/releases/download/${{ env.VERSION }}/clickup-tui-apple-darwnin-silicone-${{ env.VERSION }}.tar.gz
          create-pullrequest: false
          commit-message: |
            chore(release): {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
