name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          release-type: go

  artifacts:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: linux-arm64
            goos: linux
            goarch: arm64
          - target: linux-arm
            goos: linux
            goarch: arm
          - target: linux-amd64
            goos: linux
            goarch: amd64
          - target: linux-arm64
            goos: linux
            goarch: arm64
          - target: apple-darwnin-silicone
            goos: darwin
            goarch: arm64
          - target: apple-darwnin-intel
            goos: darwin
            goarch: amd64
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1

      - name: Build the binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          TARGET: ${{ matrix.target }}
        run: go build -o bin/clickup-tui-"${TARGET}

      - name: "Tar files"
        if: startsWith(github.ref, 'refs/tags/v')
        run: tar -cvf my_files.tar /path/to/my/directory

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./bin
