name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  artifacts:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: linux-arm64
            goos: linux
            goarch: arm64
          - target: linux-arm
            goos: linux
            goarch: arm
          - target: linux-amd64
            goos: linux
            goarch: amd64
          - target: apple-darwnin-silicone
            goos: darwin
            goarch: arm64
          - target: apple-darwnin-intel
            goos: darwin
            goarch: amd64
    env:
      ARTIFACT_NAME: clickup-tui-${{ matrix.target }}-${{ github.event.release.tag_name }}.tar.gz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true # tmp

      - name: Build the binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: CGO_ENABLED=1 go build -o bin/clickup-tui

      - name: "Tar files"
        working-directory: bin
        run: tar -czvf "${ARTIFACT_NAME}" clickup-tui

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} bin/"${ARTIFACT_NAME}"
